New_Cycle_2.0/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace New_Cycle_2._0.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
          

            return View();
        }

        public ActionResult Contact()
        {
            

            return View();
        }

        public ActionResult tipoColaborador()
        {
           

            return View();
        }


        public ActionResult Recolector()
        {


            return View();
        }
    }
}

New_Cycle_2.0/Controllers/PuntoEntregasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using New_Cycle_2._0;

namespace New_Cycle_2._0.Controllers
{
    public class PuntoEntregasController : Controller
    {
        private New_cycle_Com_RecoEntities db = new New_cycle_Com_RecoEntities();

        // GET: PuntoEntregas
        public ActionResult Index()
        {
            return View(db.PuntoEntrega.ToList());
        }

        // GET: PuntoEntregas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PuntoEntrega puntoEntrega = db.PuntoEntrega.Find(id);
            if (puntoEntrega == null)
            {
                return HttpNotFound();
            }
            return View(puntoEntrega);
        }

        // GET: PuntoEntregas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PuntoEntregas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PuntoEntregaID,Nombre_del_punto,Direccion,Tipo_de_residuos")] PuntoEntrega puntoEntrega)
        {
            if (ModelState.IsValid)
            {
                db.PuntoEntrega.Add(puntoEntrega);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(puntoEntrega);
        }

        // GET: PuntoEntregas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PuntoEntrega puntoEntrega = db.PuntoEntrega.Find(id);
            if (puntoEntrega == null)
            {
                return HttpNotFound();
            }
            return View(puntoEntrega);
        }

        // POST: PuntoEntregas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PuntoEntregaID,Nombre_del_punto,Direccion,Tipo_de_residuos")] PuntoEntrega puntoEntrega)
        {
            if (ModelState.IsValid)
            {
                db.Entry(puntoEntrega).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(puntoEntrega);
        }

        // GET: PuntoEntregas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PuntoEntrega puntoEntrega = db.PuntoEntrega.Find(id);
            if (puntoEntrega == null)
            {
                return HttpNotFound();
            }
            return View(puntoEntrega);
        }

        // POST: PuntoEntregas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PuntoEntrega puntoEntrega = db.PuntoEntrega.Find(id);
            db.PuntoEntrega.Remove(puntoEntrega);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

New_Cycle_2.0/Views/Home/About.cshtml
<!DOCTYPE html>
<html>
<head>

    <style>
        body {
            background-color: #CEF59B; /* Cambia el color de fondo según tus preferencias */
        }
    </style>
</head>
<body>
    <a>@Html.ActionLink("Volver", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</a>
    <a>@Html.ActionLink("Quienes somos", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</a>
    <div style="width: 1667px; height: 1024px; position: relative; background: #CEF59B">
        <div style="width: 1426px; height: 962px; left: 116px; top: 15px; position: absolute; background: rgba(255, 255, 255, 0.88)"></div>
        <img style="width: 646px; height: 589px; left: 781px; top: 356px; position: absolute" src="https://colombiaverde.com.co/wp-content/uploads/2023/03/plan-de-manejo-integral-de-residuos-solidos.jpg" />
        <div style="width: 755px; height: 131px; left: 208px; top: 49px; position: absolute; mix-blend-mode: darken; color: #65AE59; font-size: 70px; font-family: Sora; font-weight: 400; word-wrap: break-word">Ciclo de los residuos  </div>
        <div style="width: 755px; height: 131px; left: 198px; top: 175px; position: absolute; mix-blend-mode: darken; color: #743817; font-size: 28px; font-family: Sora; font-weight: 400; word-wrap: break-word">¿En qué consiste?</div>
        <div style="width: 543px; height: 256px; left: 198px; top: 614px; position: absolute; background: rgba(162.07, 221, 103.13, 0.43)"></div>
        <div style="width: 477px; height: 185px; left: 217px; top: 560px; position: absolute; text-align: justify"><span style="color: black; font-size: 20px; font-family: Imprima; font-weight: 400; word-wrap: break-word"><br /> <br /></span><span style="color: black; font-size: 20px; font-family: Imprima; font-weight: 400; word-wrap: break-word">-Generación <br />-Recolección <br />-Transporte <br />-Procesamiento <br />-Reciclaje <br />-Eliminación <br />-Gestión y planificación <br />-Educación y concientización.</span></div>
        <div style="left: 198px; top: 535px; position: absolute; text-align: justify"><span style="color: #743B17; font-size: 28px; font-family: Sora; font-weight: 400; word-wrap: break-word">Etapas del ciclo de los residuos sólidos:</span><span style="color: black; font-size: 28px; font-family: Sora; font-weight: 400; word-wrap: break-word"> </span></div>
        <div style="width: 522px; height: 245px; left: 198px; top: 231px; position: absolute; background: rgba(233.75, 199.04, 75.97, 0.43)"></div>
        <div style="width: 477px; height: 185px; left: 217px; top: 246px; position: absolute; text-align: justify; color: black; font-size: 20px; font-family: Imprima; font-weight: 400; word-wrap: break-word">El ciclo de los residuos sólidos, también conocido como ciclo de gestión integral de residuos sólidos, se refiere al proceso que sigue un residuo desde su generación hasta su disposición final. Este ciclo implica una serie de etapas que tienen como objetivo gestionar de manera adecuada los residuos sólidos para minimizar su impacto ambiental y promover la sostenibilidad. </div>
    </div>
</body>
</html>

New_Cycle_2.0/Views/Home/Contact.cshtml
<!DOCTYPE html>
<html>
<head>

    <style>
        body {
            background-color: #CEF59B; /* Cambia el color de fondo según tus preferencias */
        }

        
    </style>
</head>
<body>
    <a>@Html.ActionLink("Volver", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</a>
    <a>@Html.ActionLink("Ciclo de los residuos", "About", "Home", new { area = "" }, new { @class = "nav-link" })</a>
    <div style="width: 1667px; height: 1024px; position: relative; background: #CEF59B">
        <div style="width: 1426px; height: 962px; left: 116px; top: 15px; position: absolute; background: rgba(255, 255, 255, 0.88)"></div>
        <div style="width: 1426px; height: 962px; left: 116px; top: 15px; position: absolute; background: rgba(255, 255, 255, 0.88); border: 1px black solid"></div>
        <img style="width: 322px; height: 179px; left: 1137px; top: 84px; position: absolute" src="https://lh3.googleusercontent.com/fife/AK0iWDyQn5VUnfZJOSz-LX-oIAsHqB7hNMAtYUOvKxD-NGL-cwjgnxIUTIFuOpVzMR1lNvzBzdv4kZi4P9_e0KBjFCEwr0dIY0vnwre2hxcZr8ZzpzgOvFi0_7cimCkjPnKh6uOAZaSbKDmllaV6B7C8CIACD1YVCVbK0hVAIfKMd1HSGt6kOk8GKjO3Ph9lNK9XRX1owlDrgy7bcDfk_ojNKkaYcmZcmFok2A4L1jQhJIPQ4LpA-c4AmEn9PE5JLSSG2AokmDYE0g512g1kYcjy-GI1H6xyn4YlLnSUka3mDM-29jGY6dKMPQ_b21-ZBSFL-xsmmSfM6jY84dkCD_159dr2xB2KWVRnnwGesgE7IYtQiG5YD5c517Y_phcOY90EV37r_Vey3DrPTiYf1X67R3m4YIMz5RcKPoKgfKGt_ngQ8U_z0XTqWmCSMQaWEQ40-Th-RHSkGIDjm02v6GjDHE4sy0OPftejs37XUBMhTV-toGKdqHBn87FSyYn_eLl-bVma-oCf1WOyRHGybNyjQEz1InNRIkajWxC4mfUG-WxQC5VyNL-7Px2VGeMGltZzPUpz95m5nHEn9nk_67pDqAp2-7eUiiSj-mQHuq0NfkE_yts4sDJzUtS7ZQJrLW32TXiHUThfIJ0B2JjRhVh-3iiundO9Jn2N-E12XGlZ3iiVaUwqWRQItTl4qwuHguBSbtDMlxyJFSdrWQuPzetcooE_lfU2jYF7Or-iBSQIAqetykndWw-7xeXvhUP9_5flWPmUMmXFylhBjhzTywAXCwfYA0j3dyyv0vF_6oULX6GNfHQBdnqfon0oUAzGxDdSIII9V2djBgrpHGLy2i1JHWciwODQZztnWBcRFKOaFmnCwSKSKCLg9opDQmSM65OGN6qHKLLCezS2p_F8nA3MLnquE-BSXqphUNU1-xOgAgS7jbLltzaTfaFdXoLyPSmzUqLewu5_yN2nY4b-uFIxB7q8fXel8c3JHnSMt6LASJNTmiV2K4kg_wmY3gUaQfZSkbvTARfRoRInlIFD59P4Y5bvUwLGESUEwAZVPc_FhfHW8Dr6KsBb5rkfc0NNw_kCE7z9b2fQHr3TqckqH3CuFLmNjuNppjXjNCCPgStUulUkgZRg2YDC5lYzM680Qb46so1E5iLS_me1gtPzmTlP8MGAnWYD97xHP8iv4oMLyJoQwFp-HqS1-jKSRhuCuFfwKCw6aBjlItqNHUthOjSoUd5K47h_sC2JZrNKZoqX7njPVqXOCmVHcqc3zv7zD9ophwJt92rX-abM6ZqcQau9uRkvgYjxrj2wBpHWEwQ4UifGZR1S4YkgijOTTrOpg7EfXP8DaujvQAKTx89tp9lrGjqMhRhCBaT1ul94N0cq_lLRmxFFVNgx0AnfDgcNXc7MfAHf2bH3AJF6bVCPu-JnD6twU6g5FxHNw9ftTBmPdICXiLtAKOQMzL4j0gofujAIhhaqylevoy0Rx0nHSTBR8a5X6h6TtvKIKu6FU0POQ0Mh79plf8yjgKJk8ZEqRZm0wQzL3DiI=s320-w320-h200-p-k" />
        <div style="width: 522px; height: 373px; left: 137px; top: 516px; position: absolute">
            <div style="width: 522px; height: 373px; left: 0px; top: 0px; position: absolute; background: rgba(233.75, 199.04, 75.97, 0.43)"></div>
            <div style="width: 477px; height: 327.96px; left: 21px; top: 33.78px; position: absolute; text-align: justify; color: black; font-size: 20px; font-family: Imprima; font-weight: 400; word-wrap: break-word">Misión: <br />Nuestra misión es promover la economía circular, un modelo de producción y consumo que garantiza un crecimiento sostenible en el tiempo. Además, nos enfocamos en reducir nuestra huella de carbono, manejar integralmente los residuos y cumplir con estándares ambientales. Creemos que la protección del medio ambiente es fundamental para alimentar un mundo mejor y para lograrlo, es importante reducir, reutilizar y reciclar los residuos.</div>
        </div>
        <div style="width: 376px; height: 79px; left: 140px; top: 119px; position: absolute; mix-blend-mode: darken; color: #743B17; font-size: 40px; font-family: Sora; font-weight: 400; word-wrap: break-word">¿Quiénes somos?</div>
        <div style="width: 376px; height: 79px; left: 138px; top: 433px; position: absolute; mix-blend-mode: darken; color: #743B17; font-size: 40px; font-family: Sora; font-weight: 400; word-wrap: break-word">Misión</div>
        <div style="width: 376px; height: 79px; left: 1247px; top: 422px; position: absolute; mix-blend-mode: darken; color: #743B17; font-size: 40px; font-family: Sora; font-weight: 400; word-wrap: break-word">Visión<br /></div>
        <div style="width: 370px; height: 79px; left: 723px; top: 304px; position: absolute; mix-blend-mode: darken; color: #743B17; font-size: 39px; font-family: Sora; font-weight: 400; word-wrap: break-word">Objetivo principal</div>
        <div style="width: 560px; height: 221px; left: 124px; top: 201px; position: absolute">
            <div style="width: 560px; height: 192.83px; left: 0px; top: 0px; position: absolute; background: rgba(233.75, 199.04, 75.97, 0.43)"></div>
            <div style="width: 511.72px; height: 200.42px; left: 23.60px; top: 20.58px; position: absolute; text-align: justify; color: black; font-size: 20px; font-family: Imprima; font-weight: 400; word-wrap: break-word">Somos una empresa comprometida con la sostenibilidad y el cuidado del medio ambiente. En nuestro sitio web, ofrecemos información sobre la clasificación y seguimiento del ciclo de los residuos sólidos, así como la venta de productos que surgen de la reutilización de estos materiales. </div>
        </div>
        <div style="width: 382px; height: 442px; left: 705px; top: 381px; position: absolute">
            <div style="width: 382px; height: 442px; left: 0px; top: 0px; position: absolute; background: rgba(162.07, 221, 103.13, 0.43)"></div>
            <div style="width: 344.12px; height: 381.23px; left: 18.40px; top: 19.89px; position: absolute; text-align: justify; color: black; font-size: 20px; font-family: Imprima; font-weight: 400; word-wrap: break-word">Objetivo principal:<br />Nuestro objetivo principal es promover la economía circular, un modelo de producción y consumo que garantiza un crecimiento sostenible en el tiempo. Además, nos enfocamos en reducir nuestra huella de carbono, manejar integralmente los residuos y cumplir con estándares ambientales. Creemos que la protección del medio ambiente es fundamental para alimentar un mundo mejor y para lograrlo, es importante reducir, reutilizar y reciclar los residuos.</div>
        </div>
        <div style="width: 415px; height: 465px; left: 1103px; top: 473px; position: absolute">
            <div style="width: 415px; height: 465px; left: 0px; top: 0px; position: absolute; background: rgba(162.07, 221, 103.13, 0.43)"></div>
            <div style="width: 340.93px; height: 256.71px; left: 24.69px; top: 32.65px; position: absolute; text-align: justify; color: black; font-size: 20px; font-family: Imprima; font-weight: 400; word-wrap: break-word">Visión:<br />Nuestra visión es ser líderes en la promoción de la economía circular y la gestión sostenible de los residuos sólidos. Queremos ser reconocidos como una empresa comprometida con el medio ambiente y la sostenibilidad, y ser un ejemplo a seguir en la industria. Buscamos ser una empresa innovadora que promueve la reutilización de materiales y la reducción de residuos, y que contribuye a la construcción de un mundo más sostenible y equitativo.</div>
        </div>
    </div>





</body>
</html>

New_Cycle_2.0/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    
    <style>
        body {
            background-color: #CEF59B; /* Cambia el color de fondo según tus preferencias */
        }
    </style>
</head>
<body>
    <a>@Html.ActionLink("Quienes somos", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</a>
    <a>@Html.ActionLink("Ciclo de los residuos", "About", "Home", new { area = "" }, new { @class = "nav-link" })</a>

    <div class=e29_4>
        <div class="e39_5"></div>
        <div class="e26_30"></div><span class="e34_38">Bienvenidos</span><span class="e34_39">En nuestro sitio web, encontraras informacion sobre la clasificacion y seguimiento del ciclo de los residuos solidos, asi como la venta de productos que surgen de la reutilizacion de estos materiales. Unete a nuestra mision de promover la sostenibilidad y cuidar del medio ambiente</span>
        <div class=e36_41>
            <div class=e36_42>
                <div class=e36_43>
                    <div></div>
                </div>
            </div>
        </div>
        <div class="e36_46"></div>
        <div class="e36_47"></div>
        <div class="e61_198"></div>
    </div>

</body>
</html>

New_Cycle_2.0/Views/Home/tipoColaborador.cshtml
<div style="width: 1440px; height: 1024px; position: relative; background: white">
    <div style="width: 1440px; height: 1028px; left: 0px; top: -4px; position: absolute; background: white"></div>
    <div style="width: 704px; height: 1020px; left: 0px; top: 4px; position: absolute; background: rgba(205.84, 245.44, 155.44, 0.71); border-radius: 100px"></div>
    <div style="width: 833px; left: 775px; top: 149px; position: absolute; color: #743817; font-size: 41px; font-family: Inter; font-style: italic; font-weight: 700; word-wrap: break-word">¿Qué tipo de empleado eres?</div>
    <div style="width: 438px; height: 199px; left: 15px; top: 124px; position: absolute; background: linear-gradient(180deg, rgba(255, 255, 255, 0) 100%)"></div>
    <div style="width: 508px; height: 481px; left: 87px; top: 254px; position: absolute; background: rgba(255, 255, 255, 0.37)"></div>
    <img style="width: 500px; height: 519px; left: 95px; top: 244px; position: absolute" src="https://1000marcas.net/wp-content/uploads/2020/02/Logo-Recycle.png" />
    <div style="width: 524px; height: 534px; left: 87px; top: 244px; position: absolute; background: rgba(217, 217, 217, 0.18); border-radius: 9999px"></div>
    <img style="width: 322px; height: 179px; left: 1086px; top: 832px; position: absolute" src="https://lh3.googleusercontent.com/fife/AK0iWDyQn5VUnfZJOSz-LX-oIAsHqB7hNMAtYUOvKxD-NGL-cwjgnxIUTIFuOpVzMR1lNvzBzdv4kZi4P9_e0KBjFCEwr0dIY0vnwre2hxcZr8ZzpzgOvFi0_7cimCkjPnKh6uOAZaSbKDmllaV6B7C8CIACD1YVCVbK0hVAIfKMd1HSGt6kOk8GKjO3Ph9lNK9XRX1owlDrgy7bcDfk_ojNKkaYcmZcmFok2A4L1jQhJIPQ4LpA-c4AmEn9PE5JLSSG2AokmDYE0g512g1kYcjy-GI1H6xyn4YlLnSUka3mDM-29jGY6dKMPQ_b21-ZBSFL-xsmmSfM6jY84dkCD_159dr2xB2KWVRnnwGesgE7IYtQiG5YD5c517Y_phcOY90EV37r_Vey3DrPTiYf1X67R3m4YIMz5RcKPoKgfKGt_ngQ8U_z0XTqWmCSMQaWEQ40-Th-RHSkGIDjm02v6GjDHE4sy0OPftejs37XUBMhTV-toGKdqHBn87FSyYn_eLl-bVma-oCf1WOyRHGybNyjQEz1InNRIkajWxC4mfUG-WxQC5VyNL-7Px2VGeMGltZzPUpz95m5nHEn9nk_67pDqAp2-7eUiiSj-mQHuq0NfkE_yts4sDJzUtS7ZQJrLW32TXiHUThfIJ0B2JjRhVh-3iiundO9Jn2N-E12XGlZ3iiVaUwqWRQItTl4qwuHguBSbtDMlxyJFSdrWQuPzetcooE_lfU2jYF7Or-iBSQIAqetykndWw-7xeXvhUP9_5flWPmUMmXFylhBjhzTywAXCwfYA0j3dyyv0vF_6oULX6GNfHQBdnqfon0oUAzGxDdSIII9V2djBgrpHGLy2i1JHWciwODQZztnWBcRFKOaFmnCwSKSKCLg9opDQmSM65OGN6qHKLLCezS2p_F8nA3MLnquE-BSXqphUNU1-xOgAgS7jbLltzaTfaFdXoLyPSmzUqLewu5_yN2nY4b-uFIxB7q8fXel8c3JHnSMt6LASJNTmiV2K4kg_wmY3gUaQfZSkbvTARfRoRInlIFD59P4Y5bvUwLGESUEwAZVPc_FhfHW8Dr6KsBb5rkfc0NNw_kCE7z9b2fQHr3TqckqH3CuFLmNjuNppjXjNCCPgStUulUkgZRg2YDC5lYzM680Qb46so1E5iLS_me1gtPzmTlP8MGAnWYD97xHP8iv4oMLyJoQwFp-HqS1-jKSRhuCuFfwKCw6aBjlItqNHUthOjSoUd5K47h_sC2JZrNKZoqX7njPVqXOCmVHcqc3zv7zD9ophwJt92rX-abM6ZqcQau9uRkvgYjxrj2wBpHWEwQ4UifGZR1S4YkgijOTTrOpg7EfXP8DaujvQAKTx89tp9lrGjqMhRhCBaT1ul94N0cq_lLRmxFFVNgx0AnfDgcNXc7MfAHf2bH3AJF6bVCPu-JnD6twU6g5FxHNw9ftTBmPdICXiLtAKOQMzL4j0gofujAIhhaqylevoy0Rx0nHSTBR8a5X6h6TtvKIKu6FU0POQ0Mh79plf8yjgKJk8ZEqRZm0wQzL3DiI=s320-w320-h200-p-k" />


    <div style="width: 425px; height: 73px; left: 873px; top: 514px; position: absolute">
        <div style="width: 425px; height: 73px; left: 0px; top: 0px; position: absolute; background: rgba(233.75, 199.04, 75.97, 0.43); border-radius: 100px"></div>
        <div style="width: 329px; height: 50px; left: 60px; top: 19px; position: absolute; color: black; font-size: 30px; font-family: Inter; font-style: italic; font-weight: 700; word-wrap: break-word"><a>@Html.ActionLink("Recolectores", "Recolector", "Home", new { area = "" }, new { @class = "nav-link" })</a></div>
        <img style="width: 54px; height: 50px; left: 280px; top: 12px; position: absolute" src="https://upload.wikimedia.org/wikipedia/commons/5/5f/Simbolo_reciclar.svg" />
    </div>
    <div style="width: 421px; height: 73px; left: 863px; top: 354px; position: absolute">
        <div style="width: 421px; height: 73px; left: 0px; top: 0px; position: absolute; background: rgba(233.75, 199.04, 75.97, 0.43); border-radius: 100px"></div>
        <div style="width: 306px; height: 50px; left: 70px; top: 23px; position: absolute; color: black; font-size: 30px; font-family: Inter; font-style: italic; font-weight: 700; word-wrap: break-word"><a>@Html.ActionLink("Conductor", "Index", "PuntoEntregas", new { area = "" }, new { @class = "nav-link" })</a> </div>
        <img style="width: 51px; height: 51px; left: 258px; top: 14px; position: absolute" src="https://icones.pro/wp-content/uploads/2021/11/icone-noire-de-camion-d-expedition-et-de-livraison.png" />
    </div>

</div>