New_Cycle_2.0/Controllers/Formu_calidadController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using New_Cycle_2._0;

namespace New_Cycle_2._0.Controllers
{
    public class Formu_calidadController : Controller
    {
        private New_cycle_Com_RecoEntities db = new New_cycle_Com_RecoEntities();

        // GET: Formu_calidad
        public ActionResult Index()
        {
            var formu_calidad = db.Formu_calidad.Include(f => f.Ruta);
            return View(formu_calidad.ToList());
        }

        // GET: Formu_calidad/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Formu_calidad formu_calidad = db.Formu_calidad.Find(id);
            if (formu_calidad == null)
            {
                return HttpNotFound();
            }
            return View(formu_calidad);
        }

        // GET: Formu_calidad/Create
        public ActionResult Create()
        {
            ViewBag.RutaID = new SelectList(db.Ruta, "RutaID", "Ruta1");
            return View();
        }

        // POST: Formu_calidad/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FormularioID,Observaciones,Aspectos_a_mejorar,RutaID")] Formu_calidad formu_calidad)
        {
            if (ModelState.IsValid)
            {
                db.Formu_calidad.Add(formu_calidad);
                db.SaveChanges();
                return RedirectToAction("Index", "PuntoEntregas");
            }

            ViewBag.RutaID = new SelectList(db.Ruta, "RutaID", "Ruta1", formu_calidad.RutaID);
            return View(formu_calidad);
        }

        // GET: Formu_calidad/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Formu_calidad formu_calidad = db.Formu_calidad.Find(id);
            if (formu_calidad == null)
            {
                return HttpNotFound();
            }
            ViewBag.RutaID = new SelectList(db.Ruta, "RutaID", "Ruta1", formu_calidad.RutaID);
            return View(formu_calidad);
        }

        // POST: Formu_calidad/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FormularioID,Observaciones,Aspectos_a_mejorar,RutaID")] Formu_calidad formu_calidad)
        {
            if (ModelState.IsValid)
            {
                db.Entry(formu_calidad).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RutaID = new SelectList(db.Ruta, "RutaID", "Ruta1", formu_calidad.RutaID);
            return View(formu_calidad);
        }

        // GET: Formu_calidad/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Formu_calidad formu_calidad = db.Formu_calidad.Find(id);
            if (formu_calidad == null)
            {
                return HttpNotFound();
            }
            return View(formu_calidad);
        }

        // POST: Formu_calidad/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Formu_calidad formu_calidad = db.Formu_calidad.Find(id);
            db.Formu_calidad.Remove(formu_calidad);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

New_Cycle_2.0/Controllers/PuntoEntregasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using New_Cycle_2._0;

namespace New_Cycle_2._0.Controllers
{
    public class PuntoEntregasController : Controller
    {
        private New_cycle_Com_RecoEntities db = new New_cycle_Com_RecoEntities();

        // GET: PuntoEntregas
        public ActionResult Index()
        {
            return View(db.PuntoEntrega.ToList());
        }

        // GET: PuntoEntregas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PuntoEntrega puntoEntrega = db.PuntoEntrega.Find(id);
            if (puntoEntrega == null)
            {
                return HttpNotFound();
            }
            return View(puntoEntrega);
        }

        // GET: PuntoEntregas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PuntoEntregas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PuntoEntregaID,Nombre_del_punto,Direccion,Tipo_de_residuos")] PuntoEntrega puntoEntrega)
        {
            if (ModelState.IsValid)
            {
                db.PuntoEntrega.Add(puntoEntrega);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(puntoEntrega);
        }

        // GET: PuntoEntregas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PuntoEntrega puntoEntrega = db.PuntoEntrega.Find(id);
            if (puntoEntrega == null)
            {
                return HttpNotFound();
            }
            return View(puntoEntrega);
        }

        // POST: PuntoEntregas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PuntoEntregaID,Nombre_del_punto,Direccion,Tipo_de_residuos")] PuntoEntrega puntoEntrega)
        {
            if (ModelState.IsValid)
            {
                db.Entry(puntoEntrega).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(puntoEntrega);
        }

        // GET: PuntoEntregas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PuntoEntrega puntoEntrega = db.PuntoEntrega.Find(id);
            if (puntoEntrega == null)
            {
                return HttpNotFound();
            }
            return View(puntoEntrega);
        }

        // POST: PuntoEntregas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PuntoEntrega puntoEntrega = db.PuntoEntrega.Find(id);
            db.PuntoEntrega.Remove(puntoEntrega);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

New_Cycle_2.0/Views/PuntoEntregas/Create.cshtml
@model New_Cycle_2._0.PuntoEntrega

@{
    ViewBag.Title = "Create";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-KyZXEAg3QhqLMpG8r+Knujsl5+z0I5t9zjnv0Z+xBC+ZlA2jgIddE2mIi2JxI5O2nEJnqNiz5Z9g6GO6GUqO8g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <title>Crear Punto de entregas</title>
    <style>
        body {
            background-color: #CEF59B;
            text-align: center;
        }

        .create-container {
            width: 500px;
            margin: 0 auto;
            padding: 20px;
            background: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .create-form label, .create-form input, .create-form select, .create-form small {
            display: block;
            margin-bottom: 10px;
        }

        .create-form small {
            font-size: 14px;
        }

        .create-form button {
            background-color: #007BFF;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <div class="create-container">
        <h2>Crear Punto De Entrega</h2>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <label for="Nombre_del_punto">Nombre del Punto</label>
            @Html.EditorFor(model => model.Nombre_del_punto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre_del_punto, "", new { @class = "text-danger" })

            <label for="Direccion">Dirección</label>
            @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })

            <label for="Tipo_de_residuos">Tipo de Residuos</label>
            @Html.EditorFor(model => model.Tipo_de_residuos, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Tipo_de_residuos, "", new { @class = "text-danger" })
            <h2></h2>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-save"></i> Guardar
                    </button>
                </div>
            </div>

        }
    </div>
</body>
</html>

New_Cycle_2.0/Views/PuntoEntregas/Delete.cshtml
@model New_Cycle_2._0.PuntoEntrega

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PuntoEntrega</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre_del_punto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre_del_punto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo_de_residuos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo_de_residuos)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

New_Cycle_2.0/Views/PuntoEntregas/Details.cshtml
@model New_Cycle_2._0.PuntoEntrega

@{
    ViewBag.Title = "Details";
}

<!DOCTYPE html>
<html>
<head>
    <title>Detalles</title>
    <style>
        body {
            background-color: #D4E6F1;
            font-family: 'Arial', sans-serif;
        }

        .details-container {
            width: 50%;
            margin: 20px auto;
            padding: 20px;
            background: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h2 {
            color: #343A40;
        }

        h4 {
            color: #007BFF;
        }

        hr {
            border-top: 1px solid #007BFF;
        }

        .dl-horizontal {
            margin-top: 20px;
        }

        dt {
            font-weight: bold;
            color: #007BFF;
        }

        dd {
            margin-left: 10px;
        }

        .btn-back {
            text-decoration: none;
            color: #343A40;
            padding: 10px 20px;
            border-radius: 5px;
            border: 1px solid #343A40;
            margin-top: 20px;
            display: inline-block;
        }

            .btn-back:hover {
                background-color: #CED4DA;
            }

        .btn-google-maps {
            text-decoration: none;
            color: #fff;
            padding: 10px 20px;
            border-radius: 5px;
            background-color: #007BFF;
            display: inline-block;
        }

            .btn-google-maps:hover {
                background-color: #0056b3;
            }
    </style>
</head>
<body>
    <div class="details-container">
        <h2>Detalles</h2>

        <div>
            <h4>Punto de Entrega</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Nombre_del_punto)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Nombre_del_punto)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Direccion)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Direccion)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Tipo_de_residuos)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Tipo_de_residuos)
                </dd>
            </dl>
        </div>

        <p>
            @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-back" })
        </p>

        <h2></h2>

        <p>
            <a class="btn btn-google-maps" href="https://www.google.com/maps?q=@Html.Raw(Uri.EscapeDataString(Model.Direccion))" target="_blank">Ir a Google Maps &raquo;</a>
        </p>
    </div>
</body>
</html>

New_Cycle_2.0/Views/PuntoEntregas/Edit.cshtml
@model New_Cycle_2._0.PuntoEntrega

@{
    ViewBag.Title = "Edit";
}



    <h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>PuntoEntrega</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.PuntoEntregaID)

            <div class="form-group">
                @Html.LabelFor(model => model.Nombre_del_punto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombre_del_punto, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre_del_punto, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Tipo_de_residuos, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tipo_de_residuos, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tipo_de_residuos, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

New_Cycle_2.0/Views/PuntoEntregas/Index.cshtml
@model IEnumerable<New_Cycle_2._0.PuntoEntrega>

@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Index</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-KyZXEAg3QhqLMpG8r+Knujsl5+z0I5t9zjnv0Z+xBC+ZlA2jgIddE2mIi2JxI5O2nEJnqNiz5Z9g6GO6GUqO8g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        body {
            background-color: #CEF59B;
            font-family: 'Arial', sans-serif;
            text-align: center;
        }

        h2 {
            color: #743817;
        }

        table {
            width: 80%;
            margin: 20px auto;
            border-collapse: collapse;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 10px;
        }

        th {
            background-color: #007BFF;
            color: #fff;
        }

        td {
            background-color: #f9f9f9;
        }

        .details-link {
            text-decoration: none;
            padding: 5px 10px;
            background-color: #007BFF;
            color: #fff;
            border-radius: 5px;
        }

            .details-link:hover {
                background-color: #0056b3;
            }

        .btn-primary {
            margin-top: 20px;
            padding: 10px 20px;
            background-color: #007BFF;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
        }

            .btn-primary:hover {
                background-color: #0056b3;
            }
    </style>
</head>
<body>
    <h2>Puntos de entrega</h2>

    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre_del_punto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tipo_de_residuos)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre_del_punto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Direccion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tipo_de_residuos)
                </td>
                <td>
                    <a href="@Url.Action("Details", new { id = item.PuntoEntregaID })" class="details-link">Detalles</a>
                </td>
            </tr>
        }
    </table>

    <a href="@Url.Action("Create", "Formu_calidad")" class="btn-primary">Realizar Formulario de calidad</a>
</body>
</html>