New_Cycle_2.0/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using New_Cycle_2._0;

namespace New_Cycle_2._0.Controllers
{
    public class ComprasController : Controller
    {
        private New_cycle_Com_RecoEntities db = new New_cycle_Com_RecoEntities();

        // GET: Compras
        public ActionResult Index()
        {
            var compras = db.Compras.Include(c => c.Metodos_de_pago).Include(c => c.Productos);
            return View(compras.ToList());
        }

        // GET: Compras/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compras compras = db.Compras.Find(id);
            if (compras == null)
            {
                return HttpNotFound();
            }
            return View(compras);
        }

        // GET: Compras/Create
        public ActionResult Create()
        {
            ViewBag.Metodo_de_pagoID = new SelectList(db.Metodos_de_pago, "Metodo_de_pagoID", "Metodo_de_pago");
            ViewBag.ProductoID = new SelectList(db.Productos, "ProductoID", "Producto");
            return View();
        }

        // POST: Compras/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FacturaID,ProductoID,Metodo_de_pagoID")] Compras compras)
        {
            if (ModelState.IsValid)
            {
                db.Compras.Add(compras);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Metodo_de_pagoID = new SelectList(db.Metodos_de_pago, "Metodo_de_pagoID", "Metodo_de_pago", compras.Metodo_de_pagoID);
            ViewBag.ProductoID = new SelectList(db.Productos, "ProductoID", "Producto", compras.ProductoID);
            return View(compras);
        }

        // GET: Compras/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compras compras = db.Compras.Find(id);
            if (compras == null)
            {
                return HttpNotFound();
            }
            ViewBag.Metodo_de_pagoID = new SelectList(db.Metodos_de_pago, "Metodo_de_pagoID", "Metodo_de_pago", compras.Metodo_de_pagoID);
            ViewBag.ProductoID = new SelectList(db.Productos, "ProductoID", "Producto", compras.ProductoID);
            return View(compras);
        }

        // POST: Compras/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FacturaID,ProductoID,Metodo_de_pagoID")] Compras compras)
        {
            if (ModelState.IsValid)
            {
                db.Entry(compras).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Metodo_de_pagoID = new SelectList(db.Metodos_de_pago, "Metodo_de_pagoID", "Metodo_de_pago", compras.Metodo_de_pagoID);
            ViewBag.ProductoID = new SelectList(db.Productos, "ProductoID", "Producto", compras.ProductoID);
            return View(compras);
        }

        // GET: Compras/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compras compras = db.Compras.Find(id);
            if (compras == null)
            {
                return HttpNotFound();
            }
            return View(compras);
        }

        // POST: Compras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Compras compras = db.Compras.Find(id);
            db.Compras.Remove(compras);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

New_Cycle_2.0/Controllers/IntercambiosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using New_Cycle_2._0;

namespace New_Cycle_2._0.Controllers
{
    public class IntercambiosController : Controller
    {
        private New_CycleEntities db = new New_CycleEntities();

        // GET: Intercambios
        public ActionResult Index()
        {
            var intercambio = db.Intercambio.Include(i => i.Empresas).Include(i => i.Producto_a_intercambiar).Include(i => i.Producto_intercambiado);
            return View(intercambio.ToList());
        }

        // GET: Intercambios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Intercambio intercambio = db.Intercambio.Find(id);
            if (intercambio == null)
            {
                return HttpNotFound();
            }
            return View(intercambio);
        }

        // GET: Intercambios/Create
        public ActionResult Create()
        {
            ViewBag.EmpresaID = new SelectList(db.Empresas, "EmpresaID", "Nombre_empresa");
            ViewBag.ProductoAInterID = new SelectList(db.Producto_a_intercambiar, "ProductoAInterID", "Nombre_del_producto_a_intercambiar");
            ViewBag.ProductoInterID = new SelectList(db.Producto_intercambiado, "ProductoInterID", "Nombre_del_producto_intercambiado");
            return View();
        }

        // POST: Intercambios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IntercambioID,EmpresaID,ProductoAInterID,ProductoInterID,Descripcion_del_intercambio")] Intercambio intercambio)
        {
            if (ModelState.IsValid)
            {
                db.Intercambio.Add(intercambio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmpresaID = new SelectList(db.Empresas, "EmpresaID", "Nombre_empresa", intercambio.EmpresaID);
            ViewBag.ProductoAInterID = new SelectList(db.Producto_a_intercambiar, "ProductoAInterID", "Nombre_del_producto_a_intercambiar", intercambio.ProductoAInterID);
            ViewBag.ProductoInterID = new SelectList(db.Producto_intercambiado, "ProductoInterID", "Nombre_del_producto_intercambiado", intercambio.ProductoInterID);
            return View(intercambio);
        }

        // GET: Intercambios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Intercambio intercambio = db.Intercambio.Find(id);
            if (intercambio == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmpresaID = new SelectList(db.Empresas, "EmpresaID", "Nombre_empresa", intercambio.EmpresaID);
            ViewBag.ProductoAInterID = new SelectList(db.Producto_a_intercambiar, "ProductoAInterID", "Nombre_del_producto_a_intercambiar", intercambio.ProductoAInterID);
            ViewBag.ProductoInterID = new SelectList(db.Producto_intercambiado, "ProductoInterID", "Nombre_del_producto_intercambiado", intercambio.ProductoInterID);
            return View(intercambio);
        }

        // POST: Intercambios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IntercambioID,EmpresaID,ProductoAInterID,ProductoInterID,Descripcion_del_intercambio")] Intercambio intercambio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(intercambio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmpresaID = new SelectList(db.Empresas, "EmpresaID", "Nombre_empresa", intercambio.EmpresaID);
            ViewBag.ProductoAInterID = new SelectList(db.Producto_a_intercambiar, "ProductoAInterID", "Nombre_del_producto_a_intercambiar", intercambio.ProductoAInterID);
            ViewBag.ProductoInterID = new SelectList(db.Producto_intercambiado, "ProductoInterID", "Nombre_del_producto_intercambiado", intercambio.ProductoInterID);
            return View(intercambio);
        }

        // GET: Intercambios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Intercambio intercambio = db.Intercambio.Find(id);
            if (intercambio == null)
            {
                return HttpNotFound();
            }
            return View(intercambio);
        }

        // POST: Intercambios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Intercambio intercambio = db.Intercambio.Find(id);
            db.Intercambio.Remove(intercambio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

New_Cycle_2.0/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using New_Cycle_2._0;

namespace New_Cycle_2._0.Controllers
{
    public class ProductosController : Controller
    {
        private New_cycle_Com_RecoEntities db = new New_cycle_Com_RecoEntities();

        // GET: Productos
        public ActionResult Index()
        {
            return View(db.Productos.ToList());
        }

        // GET: Productos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Productos productos = db.Productos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // GET: Productos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Productos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductoID,Producto")] Productos productos)
        {
            if (ModelState.IsValid)
            {
                db.Productos.Add(productos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productos);
        }

        // GET: Productos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Productos productos = db.Productos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // POST: Productos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductoID,Producto")] Productos productos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productos);
        }

        // GET: Productos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Productos productos = db.Productos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Productos productos = db.Productos.Find(id);
            db.Productos.Remove(productos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

New_Cycle_2.0/Views/Usuarios/Admin.cshtml
<div style="width: 1440px; height: 1024px; background: white; justify-content: center; align-items: center; display: inline-flex">
    <div style="width: 1440px; height: 1028px; position: relative">
        <div style="width: 1440px; height: 1028px; left: 0px; top: 0px; position: absolute; background: white"></div>
        <div style="width: 704px; height: 1020px; left: 0px; top: 8px; position: absolute; background: rgba(205.84, 245.44, 155.44, 0.71); border-radius: 100px"></div>
        <div style="width: 638px; height: 73px; left: 770px; top: 499px; position: absolute; background: rgba(233.75, 199.04, 75.97, 0.43); border-radius: 100px"></div>
        <div style="width: 638px; height: 73px; left: 773px; top: 395px; position: absolute; background: rgba(233.75, 199.04, 75.97, 0.43); border-radius: 100px"></div>
        <div style="left: 749px; top: 233px; position: absolute; color: #743817; font-size: 41px; font-family: Inter; font-style: italic; font-weight: 700; word-wrap: break-word">Hola Admin ¿Que deseas hacer?</div>
        <div style="width: 438px; height: 199px; left: 15px; top: 128px; position: absolute; background: linear-gradient(180deg, rgba(255, 255, 255, 0) 100%)"></div>
        <div style="width: 638px; height: 73px; left: 770px; top: 709px; position: absolute; background: rgba(233.75, 199.04, 75.97, 0.43); border-radius: 100px"></div>
        <div style="width: 638px; height: 73px; left: 770px; top: 603px; position: absolute; background: rgba(233.75, 199.04, 75.97, 0.43); border-radius: 100px"></div>
        <div style="width: 501px; height: 50px; left: 860px; top: 522px; position: absolute; color: rgba(0, 0, 0, 0.70); font-size: 30px; font-family: Inter; font-style: italic; font-weight: 700; word-wrap: break-word">@Html.ActionLink("Productos de compra", "Index", "Productos", new { area = "" }, new { @class = "nav-link" })</div>
        <div style="width: 394px; height: 50px; left: 860px; top: 416px; position: absolute; color: rgba(0, 0, 0, 0.70); font-size: 30px; font-family: Inter; font-style: italic; font-weight: 700; word-wrap: break-word">@Html.ActionLink("Crear puntos de entrega", "Create", "PuntoEntregas", new { area = "" }, new { @class = "nav-link" })</div>
        <div style="width: 329px; height: 50px; left: 846px; top: 727px; position: absolute; color: rgba(0, 0, 0, 0.70); font-size: 30px; font-family: Inter; font-style: italic; font-weight: 700; word-wrap: break-word">@Html.ActionLink("Rutas", "Index", "Rutas", new { area = "" }, new { @class = "nav-link" })</div>
        <div style="width: 507px; height: 50px; left: 838px; top: 626px; position: absolute; color: rgba(0, 0, 0, 0.70); font-size: 30px; font-family: Inter; font-style: italic; font-weight: 700; word-wrap: break-word">@Html.ActionLink("Productos de intercambio", "Index", "Producto_intercambiado", new { area = "" }, new { @class = "nav-link" })</div>
        <div style="width: 508px; height: 481px; left: 87px; top: 258px; position: absolute; background: rgba(255, 255, 255, 0.37)"></div>
        <img style="width: 500px; height: 519px; left: 95px; top: 248px; position: absolute" src="https://1000marcas.net/wp-content/uploads/2020/02/Logo-Recycle.png" />
        <div style="width: 524px; height: 534px; left: 87px; top: 248px; position: absolute; background: rgba(217, 217, 217, 0.18); border-radius: 9999px"></div>
        <img style="width: 322px; height: 179px; left: 30px; top: 19px; position: absolute" src="https://lh3.googleusercontent.com/fife/AK0iWDyQn5VUnfZJOSz-LX-oIAsHqB7hNMAtYUOvKxD-NGL-cwjgnxIUTIFuOpVzMR1lNvzBzdv4kZi4P9_e0KBjFCEwr0dIY0vnwre2hxcZr8ZzpzgOvFi0_7cimCkjPnKh6uOAZaSbKDmllaV6B7C8CIACD1YVCVbK0hVAIfKMd1HSGt6kOk8GKjO3Ph9lNK9XRX1owlDrgy7bcDfk_ojNKkaYcmZcmFok2A4L1jQhJIPQ4LpA-c4AmEn9PE5JLSSG2AokmDYE0g512g1kYcjy-GI1H6xyn4YlLnSUka3mDM-29jGY6dKMPQ_b21-ZBSFL-xsmmSfM6jY84dkCD_159dr2xB2KWVRnnwGesgE7IYtQiG5YD5c517Y_phcOY90EV37r_Vey3DrPTiYf1X67R3m4YIMz5RcKPoKgfKGt_ngQ8U_z0XTqWmCSMQaWEQ40-Th-RHSkGIDjm02v6GjDHE4sy0OPftejs37XUBMhTV-toGKdqHBn87FSyYn_eLl-bVma-oCf1WOyRHGybNyjQEz1InNRIkajWxC4mfUG-WxQC5VyNL-7Px2VGeMGltZzPUpz95m5nHEn9nk_67pDqAp2-7eUiiSj-mQHuq0NfkE_yts4sDJzUtS7ZQJrLW32TXiHUThfIJ0B2JjRhVh-3iiundO9Jn2N-E12XGlZ3iiVaUwqWRQItTl4qwuHguBSbtDMlxyJFSdrWQuPzetcooE_lfU2jYF7Or-iBSQIAqetykndWw-7xeXvhUP9_5flWPmUMmXFylhBjhzTywAXCwfYA0j3dyyv0vF_6oULX6GNfHQBdnqfon0oUAzGxDdSIII9V2djBgrpHGLy2i1JHWciwODQZztnWBcRFKOaFmnCwSKSKCLg9opDQmSM65OGN6qHKLLCezS2p_F8nA3MLnquE-BSXqphUNU1-xOgAgS7jbLltzaTfaFdXoLyPSmzUqLewu5_yN2nY4b-uFIxB7q8fXel8c3JHnSMt6LASJNTmiV2K4kg_wmY3gUaQfZSkbvTARfRoRInlIFD59P4Y5bvUwLGESUEwAZVPc_FhfHW8Dr6KsBb5rkfc0NNw_kCE7z9b2fQHr3TqckqH3CuFLmNjuNppjXjNCCPgStUulUkgZRg2YDC5lYzM680Qb46so1E5iLS_me1gtPzmTlP8MGAnWYD97xHP8iv4oMLyJoQwFp-HqS1-jKSRhuCuFfwKCw6aBjlItqNHUthOjSoUd5K47h_sC2JZrNKZoqX7njPVqXOCmVHcqc3zv7zD9ophwJt92rX-abM6ZqcQau9uRkvgYjxrj2wBpHWEwQ4UifGZR1S4YkgijOTTrOpg7EfXP8DaujvQAKTx89tp9lrGjqMhRhCBaT1ul94N0cq_lLRmxFFVNgx0AnfDgcNXc7MfAHf2bH3AJF6bVCPu-JnD6twU6g5FxHNw9ftTBmPdICXiLtAKOQMzL4j0gofujAIhhaqylevoy0Rx0nHSTBR8a5X6h6TtvKIKu6FU0POQ0Mh79plf8yjgKJk8ZEqRZm0wQzL3DiI=s320-w320-h200-p-k" />
    </div>
</div>

New_Cycle_2.0/Views/Usuarios/Comerzalizacion.cshtml
<div style="width: 1440px; height: 1024px; position: relative; background: white">
    <div style="width: 1440px; height: 1028px; left: 0px; top: -4px; position: absolute; background: white"></div>
    <div style="width: 704px; height: 1020px; left: 0px; top: 4px; position: absolute; background: rgba(1.02, 185.97, 244.37, 0.26); border-radius: 100px"></div>
    <div style="width: 638px; height: 73px; left: 770px; top: 377px; position: absolute; background: rgba(171.26, 166.14, 148, 0.43); border-radius: 100px"></div>
    <div style="left: 854px; top: 124px; position: absolute; color: black; font-size: 48px; font-family: Inter; font-style: italic; font-weight: 700; word-wrap: break-word">¿Qué deseas hacer?</div>
    <div style="width: 638px; height: 73px; left: 770px; top: 493px; position: absolute; background: #D9D9D9; border-radius: 100px"></div>
    <div style="width: 486px; height: 50px; left: 825px; top: 393px; position: absolute; color: black; font-size: 30px; font-family: Inter; font-style: italic; font-weight: 700; word-wrap: break-word"><a>@Html.ActionLink("Intercambio de materiales", "Index", "Intercambios", new { area = "" }, new { @class = "nav-link" })</a></div>
    <div style="width: 484px; height: 50px; left: 825px; top: 510px; position: absolute; color: black; font-size: 30px; font-family: Inter; font-style: italic; font-weight: 700; word-wrap: break-word"><a>@Html.ActionLink("Compra de productos", "Index", "Compras", new { area = "" }, new { @class = "nav-link" })</a></div>
    <div style="width: 508px; height: 481px; left: 87px; top: 254px; position: absolute; background: rgba(255, 255, 255, 0.37)"></div>
    <div style="width: 524px; height: 534px; left: 71px; top: 243px; position: absolute; background: rgba(217, 217, 217, 0.18); border-radius: 9999px"></div>
    <img style="width: 500px; height: 519px; left: 95px; top: 244px; position: absolute" src="https://1000marcas.net/wp-content/uploads/2020/02/Logo-Recycle.png" />
   
    <img style="width: 322px; height: 179px; left: -27px; top: 35px; position: absolute" src="https://lh3.googleusercontent.com/fife/AK0iWDyQn5VUnfZJOSz-LX-oIAsHqB7hNMAtYUOvKxD-NGL-cwjgnxIUTIFuOpVzMR1lNvzBzdv4kZi4P9_e0KBjFCEwr0dIY0vnwre2hxcZr8ZzpzgOvFi0_7cimCkjPnKh6uOAZaSbKDmllaV6B7C8CIACD1YVCVbK0hVAIfKMd1HSGt6kOk8GKjO3Ph9lNK9XRX1owlDrgy7bcDfk_ojNKkaYcmZcmFok2A4L1jQhJIPQ4LpA-c4AmEn9PE5JLSSG2AokmDYE0g512g1kYcjy-GI1H6xyn4YlLnSUka3mDM-29jGY6dKMPQ_b21-ZBSFL-xsmmSfM6jY84dkCD_159dr2xB2KWVRnnwGesgE7IYtQiG5YD5c517Y_phcOY90EV37r_Vey3DrPTiYf1X67R3m4YIMz5RcKPoKgfKGt_ngQ8U_z0XTqWmCSMQaWEQ40-Th-RHSkGIDjm02v6GjDHE4sy0OPftejs37XUBMhTV-toGKdqHBn87FSyYn_eLl-bVma-oCf1WOyRHGybNyjQEz1InNRIkajWxC4mfUG-WxQC5VyNL-7Px2VGeMGltZzPUpz95m5nHEn9nk_67pDqAp2-7eUiiSj-mQHuq0NfkE_yts4sDJzUtS7ZQJrLW32TXiHUThfIJ0B2JjRhVh-3iiundO9Jn2N-E12XGlZ3iiVaUwqWRQItTl4qwuHguBSbtDMlxyJFSdrWQuPzetcooE_lfU2jYF7Or-iBSQIAqetykndWw-7xeXvhUP9_5flWPmUMmXFylhBjhzTywAXCwfYA0j3dyyv0vF_6oULX6GNfHQBdnqfon0oUAzGxDdSIII9V2djBgrpHGLy2i1JHWciwODQZztnWBcRFKOaFmnCwSKSKCLg9opDQmSM65OGN6qHKLLCezS2p_F8nA3MLnquE-BSXqphUNU1-xOgAgS7jbLltzaTfaFdXoLyPSmzUqLewu5_yN2nY4b-uFIxB7q8fXel8c3JHnSMt6LASJNTmiV2K4kg_wmY3gUaQfZSkbvTARfRoRInlIFD59P4Y5bvUwLGESUEwAZVPc_FhfHW8Dr6KsBb5rkfc0NNw_kCE7z9b2fQHr3TqckqH3CuFLmNjuNppjXjNCCPgStUulUkgZRg2YDC5lYzM680Qb46so1E5iLS_me1gtPzmTlP8MGAnWYD97xHP8iv4oMLyJoQwFp-HqS1-jKSRhuCuFfwKCw6aBjlItqNHUthOjSoUd5K47h_sC2JZrNKZoqX7njPVqXOCmVHcqc3zv7zD9ophwJt92rX-abM6ZqcQau9uRkvgYjxrj2wBpHWEwQ4UifGZR1S4YkgijOTTrOpg7EfXP8DaujvQAKTx89tp9lrGjqMhRhCBaT1ul94N0cq_lLRmxFFVNgx0AnfDgcNXc7MfAHf2bH3AJF6bVCPu-JnD6twU6g5FxHNw9ftTBmPdICXiLtAKOQMzL4j0gofujAIhhaqylevoy0Rx0nHSTBR8a5X6h6TtvKIKu6FU0POQ0Mh79plf8yjgKJk8ZEqRZm0wQzL3DiI=s320-w320-h200-p-k" />
</div>

New_Cycle_2.0/Views/Usuarios/Delete.cshtml
@model New_Cycle_2._0.Usuarios

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Usuarios</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contraseña)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contraseña)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tipo_de_Usuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tipo_de_Usuario)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>