New_Cycle_2.0/Controllers/IntercambiosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using New_Cycle_2._0;

namespace New_Cycle_2._0.Controllers
{
    public class IntercambiosController : Controller
    {
        private New_CycleEntities db = new New_CycleEntities();

        // GET: Intercambios
        public ActionResult Index()
        {
            var intercambio = db.Intercambio.Include(i => i.Empresas).Include(i => i.Producto_a_intercambiar).Include(i => i.Producto_intercambiado);
            return View(intercambio.ToList());
        }

        // GET: Intercambios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Intercambio intercambio = db.Intercambio.Find(id);
            if (intercambio == null)
            {
                return HttpNotFound();
            }
            return View(intercambio);
        }

        // GET: Intercambios/Create
        public ActionResult Create()
        {
            ViewBag.EmpresaID = new SelectList(db.Empresas, "EmpresaID", "Nombre_empresa");
            ViewBag.ProductoAInterID = new SelectList(db.Producto_a_intercambiar, "ProductoAInterID", "Nombre_del_producto_a_intercambiar");
            ViewBag.ProductoInterID = new SelectList(db.Producto_intercambiado, "ProductoInterID", "Nombre_del_producto_intercambiado");
            return View();
        }

        // POST: Intercambios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IntercambioID,EmpresaID,ProductoAInterID,ProductoInterID,Descripcion_del_intercambio")] Intercambio intercambio)
        {
            if (ModelState.IsValid)
            {
                db.Intercambio.Add(intercambio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmpresaID = new SelectList(db.Empresas, "EmpresaID", "Nombre_empresa", intercambio.EmpresaID);
            ViewBag.ProductoAInterID = new SelectList(db.Producto_a_intercambiar, "ProductoAInterID", "Nombre_del_producto_a_intercambiar", intercambio.ProductoAInterID);
            ViewBag.ProductoInterID = new SelectList(db.Producto_intercambiado, "ProductoInterID", "Nombre_del_producto_intercambiado", intercambio.ProductoInterID);
            return View(intercambio);
        }

        // GET: Intercambios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Intercambio intercambio = db.Intercambio.Find(id);
            if (intercambio == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmpresaID = new SelectList(db.Empresas, "EmpresaID", "Nombre_empresa", intercambio.EmpresaID);
            ViewBag.ProductoAInterID = new SelectList(db.Producto_a_intercambiar, "ProductoAInterID", "Nombre_del_producto_a_intercambiar", intercambio.ProductoAInterID);
            ViewBag.ProductoInterID = new SelectList(db.Producto_intercambiado, "ProductoInterID", "Nombre_del_producto_intercambiado", intercambio.ProductoInterID);
            return View(intercambio);
        }

        // POST: Intercambios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IntercambioID,EmpresaID,ProductoAInterID,ProductoInterID,Descripcion_del_intercambio")] Intercambio intercambio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(intercambio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmpresaID = new SelectList(db.Empresas, "EmpresaID", "Nombre_empresa", intercambio.EmpresaID);
            ViewBag.ProductoAInterID = new SelectList(db.Producto_a_intercambiar, "ProductoAInterID", "Nombre_del_producto_a_intercambiar", intercambio.ProductoAInterID);
            ViewBag.ProductoInterID = new SelectList(db.Producto_intercambiado, "ProductoInterID", "Nombre_del_producto_intercambiado", intercambio.ProductoInterID);
            return View(intercambio);
        }

        // GET: Intercambios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Intercambio intercambio = db.Intercambio.Find(id);
            if (intercambio == null)
            {
                return HttpNotFound();
            }
            return View(intercambio);
        }

        // POST: Intercambios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Intercambio intercambio = db.Intercambio.Find(id);
            db.Intercambio.Remove(intercambio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

New_Cycle_2.0/Controllers/Producto_a_intercambiarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using New_Cycle_2._0;

namespace New_Cycle_2._0.Controllers
{
    public class Producto_a_intercambiarController : Controller
    {
        private New_CycleEntities db = new New_CycleEntities();

        // GET: Producto_a_intercambiar
        public ActionResult Index()
        {
            return View(db.Producto_a_intercambiar.ToList());
        }

        // GET: Producto_a_intercambiar/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto_a_intercambiar producto_a_intercambiar = db.Producto_a_intercambiar.Find(id);
            if (producto_a_intercambiar == null)
            {
                return HttpNotFound();
            }
            return View(producto_a_intercambiar);
        }

        // GET: Producto_a_intercambiar/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Producto_a_intercambiar/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductoAInterID,Nombre_del_producto_a_intercambiar")] Producto_a_intercambiar producto_a_intercambiar)
        {
            if (ModelState.IsValid)
            {
                db.Producto_a_intercambiar.Add(producto_a_intercambiar);
                db.SaveChanges();
                return RedirectToAction("Index", "Intercambios");
            }

            return View(producto_a_intercambiar);
        }

        // GET: Producto_a_intercambiar/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto_a_intercambiar producto_a_intercambiar = db.Producto_a_intercambiar.Find(id);
            if (producto_a_intercambiar == null)
            {
                return HttpNotFound();
            }
            return View(producto_a_intercambiar);
        }

        // POST: Producto_a_intercambiar/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductoAInterID,Nombre_del_producto_a_intercambiar")] Producto_a_intercambiar producto_a_intercambiar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(producto_a_intercambiar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(producto_a_intercambiar);
        }

        // GET: Producto_a_intercambiar/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto_a_intercambiar producto_a_intercambiar = db.Producto_a_intercambiar.Find(id);
            if (producto_a_intercambiar == null)
            {
                return HttpNotFound();
            }
            return View(producto_a_intercambiar);
        }

        // POST: Producto_a_intercambiar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Producto_a_intercambiar producto_a_intercambiar = db.Producto_a_intercambiar.Find(id);
            db.Producto_a_intercambiar.Remove(producto_a_intercambiar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

New_Cycle_2.0/Views/Intercambios/Create.cshtml
@model New_Cycle_2._0.Intercambio

@{
    ViewBag.Title = "Create";
}

<!DOCTYPE html>
<html>
<head>
    <title>Crear</title>
    <style>
        body {
            background-color: #ACEBFF; /* Cambia el color de fondo según tus preferencias */
        }
        .action-links {
            text-decoration: none;
            padding: 10px 20px;
            background-color: #007BFF;
            color: #fff;
            border-radius: 5px;
            margin-right: 10px;
        }

            .action-links:hover {
                background-color: #0056b3;
            }
    </style>
</head>
<body>

  

    <h2>Crear</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Intercambio</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.EmpresaID, "Empresa asociada", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("EmpresaID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.EmpresaID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductoAInterID, "Producto a entregar", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ProductoAInterID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ProductoAInterID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductoInterID, "Producto a recibir", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ProductoInterID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ProductoInterID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Descripcion_del_intercambio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Descripcion_del_intercambio, new { @class = "form-control", @style = "height: 150px;" })
            @Html.ValidationMessageFor(model => model.Descripcion_del_intercambio, "", new { @class = "text-danger" })
        </div>
    </div>

    <h2></h2>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear Intercambio" class="action-links" />
        </div>
    </div>
</div>
    }

    <div>
        @Html.ActionLink("Regresar a la lista", "Index")
    </div>


</body>
</html>

New_Cycle_2.0/Views/Intercambios/Delete.cshtml
@model New_Cycle_2._0.Intercambio

@{
    ViewBag.Title = "Delete";
}

<!DOCTYPE html>
<html>
<head>
    <title>Delete</title>
    <style>
        body {
            background-color: #FADBD8;
            font-family: 'Arial', sans-serif;
        }

        .delete-container {
            width: 50%;
            margin: 20px auto;
            padding: 20px;
            background: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h2, h3 {
            color: #B03A2E;
        }

        dl {
            display: flex;
            flex-wrap: wrap;
        }

        dt, dd {
            flex: 0 1 48%;
            padding: 10px;
        }

        .form-actions {
            margin-top: 20px;
            display: flex;
            justify-content: space-between;
        }

        .delete-link {
            background-color: #B03A2E;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }

            .delete-link:hover {
                background-color: #943126;
            }

        .btn-back {
            text-decoration: none;
            color: #B03A2E;
            padding: 10px 20px;
            border-radius: 5px;
            border: 1px solid #B03A2E;
        }

            .btn-back:hover {
                background-color: #F1948A;
            }
    </style>
</head>
<body>
    <div class="delete-container">
        <h2>Eliminar</h2>
        <h3>Estas seguro?</h3>

        <div>
            <h4>Intercambio</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Descripcion_del_intercambio)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Descripcion_del_intercambio)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Empresas.Nombre_empresa)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Empresas.Nombre_empresa)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Producto_a_intercambiar.Nombre_del_producto_a_intercambiar)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Producto_a_intercambiar.Nombre_del_producto_a_intercambiar)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Producto_intercambiado.Nombre_del_producto_intercambiado)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Producto_intercambiado.Nombre_del_producto_intercambiado)
                </dd>
            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions">
                    <input type="submit" value="Eliminar" class="delete-link" />
                    @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-back" })
                </div>
            }
        </div>
    </div>
</body>
</html>

New_Cycle_2.0/Views/Intercambios/Details.cshtml
@model New_Cycle_2._0.Intercambio

@{
    ViewBag.Title = "Details";
}

<!DOCTYPE html>
<html>
<head>
    <title>Detalles del intercambio</title>
    <style>
        body {
            background-color: #ACEBFF; /* Cambia el color de fondo según tus preferencias */
        }
    </style>
</head>
<body>

    <h2>Detalles del intercambio</h2>

    <div>
        <h4>Intercambio</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Descripcion_del_intercambio)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Descripcion_del_intercambio)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Empresas.Nombre_empresa)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Empresas.Nombre_empresa)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Producto_a_intercambiar.Nombre_del_producto_a_intercambiar)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Producto_a_intercambiar.Nombre_del_producto_a_intercambiar)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Producto_intercambiado.Nombre_del_producto_intercambiado)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Producto_intercambiado.Nombre_del_producto_intercambiado)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Editar", "Edit", new { id = Model.IntercambioID }) |
        @Html.ActionLink("Regresar a la lista", "Index")
    </p>

</body>
</html>

New_Cycle_2.0/Views/Intercambios/Edit.cshtml
@model New_Cycle_2._0.Intercambio

@{
    ViewBag.Title = "Edit";
}

<!DOCTYPE html>
<html>
<head>
    <title>Editar el intercambio</title>
    <style>
        body {
            background-color: #D4E6F1;
            font-family: 'Arial', sans-serif;
        }

        .edit-container {
            width: 50%;
            margin: 20px auto;
            padding: 20px;
            background: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h2 {
            color: #3498DB;
        }

        .form-horizontal {
            margin-top: 20px;
        }

        .form-group {
            margin-bottom: 20px;
        }

        .control-label {
            font-weight: bold;
            color: #3498DB;
        }

        .form-control {
            width: 100%;
            padding: 10px;
            box-sizing: border-box;
            border: 1px solid #3498DB;
            border-radius: 5px;
            margin-top: 5px;
        }

        .action-links {
            background-color: #3498DB;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
        }

            .action-links:hover {
                background-color: #2980B9;
            }

        .btn-back {
            text-decoration: none;
            color: #3498DB;
            padding: 10px 20px;
            border-radius: 5px;
            border: 1px solid #3498DB;
        }

            .btn-back:hover {
                background-color: #AED6F1;
            }
    </style>
</head>
<body>
    <div class="edit-container">
        <h2>Editar el intercambio</h2>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Intercambio</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IntercambioID)

                <div class="form-group">
                    @Html.LabelFor(model => model.EmpresaID, "Empresa asociada", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.EmpresaID, ViewBag.EmpresaList as SelectList, "Seleccione", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.EmpresaID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProductoAInterID, "Producto a entregar", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.ProductoAInterID, ViewBag.ProductoAInterList as SelectList, "Seleccione", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ProductoAInterID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProductoInterID, "Producto a recibir", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.ProductoInterID, ViewBag.ProductoInterList as SelectList, "Seleccione", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ProductoInterID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Descripcion_del_intercambio, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Descripcion_del_intercambio, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Descripcion_del_intercambio, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Guardar" class="action-links" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Regresar a la lista", "Index", null, new { @class = "btn btn-back" })
        </div>
    </div>
</body>
</html>

New_Cycle_2.0/Views/Intercambios/Index.cshtml
@model IEnumerable<New_Cycle_2._0.Intercambio>

@{
    ViewBag.Title = "Intercambios";
}

<!DOCTYPE html>
<html>
<head>
    <title>Intercambios</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-KyZXEAg3QhqLMpG8r+Knujsl5+z0I5t9zjnv0Z+xBC+ZlA2jgIddE2mIi2JxI5O2nEJnqNiz5Z9g6GO6GUqO8g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        body {
            background-color: #ACEBFF;
            text-align: center;
            font-family: Arial, sans-serif;
        }
        .index-container {
            width: 80%;
            margin: 20px auto;
            background: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
        }

        h2 {
            color: #743817;
        }

        p {
            margin-top: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #007BFF;
            
        }

        td {
            background-color: #f9f9f9;
        }

        .action-links {
            text-decoration: none;
            padding: 10px 20px;
            background-color: #007BFF;
            color: #fff;
            border-radius: 5px;
            margin-right: 10px;
        }

            .action-links:hover {
                background-color: #0056b3;
            }

        .delete-link {
            color: #fff;
            background-color: #dc3545;
            padding: 5px 10px;
            border-radius: 5px;
            text-decoration: none;
            display: inline-block;
        }

            .delete-link:hover {
                background-color: #c82333;
            }
    </style>
</head>
<body>
    <div class="index-container">
        <h2>Intercambios</h2>

        <p>
            <a href="@Url.Action("Create")" class="action-links">Crear nuevo intercambio</a>
        </p>
        <p>
            <a href="@Url.Action("Create", "Producto_a_intercambiar", new { area = "" })" class="action-links">Crear Nuevos Productos a entregar</a>
        </p>

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Descripcion_del_intercambio)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Empresas.Nombre_empresa)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Producto_a_intercambiar.Nombre_del_producto_a_intercambiar)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Producto_intercambiado.Nombre_del_producto_intercambiado)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion_del_intercambio)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Empresas.Nombre_empresa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Producto_a_intercambiar.Nombre_del_producto_a_intercambiar)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Producto_intercambiado.Nombre_del_producto_intercambiado)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", new { id = item.IntercambioID })" class="action-links">Editar</a>
                        <h2></h2>
                        <a href="@Url.Action("Delete", new { id = item.IntercambioID })" class="delete-link">Eliminar</a>
                    </td>
                </tr>
            }
        </table>
        </div>
</body>
</html>